### PR TITLE
Update musikernel2.desktop

### PR DESCRIPTION
**Pull request by trebmuh**
I'm pretty sure that this line is unneeded.

### CODE REVIEW

**Comment by j3ffhubb** [comment]
Which desktop environment(s) did you test with?  I'm open to removing it if none of the major DEs use it.

**Comment by trebmuh** [comment]
Hi @j3ffhubb 
I tested it with MATE.

**Comment by j3ffhubb** [comment]
Back at my computer now after a weekend of travelling;   Didn't realize when making the previous posts that the `Name[en_US]=` was redundant of `Name=`.  Since the name would not be translated, you are absolutely correct, it is not necessary.  I will accept the merge request.

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
